### ISSUE TITLE
开启后拦截不到请求

### ISSUE THREAD

**Issue by streaker303** [g0ngjie/colibri#1]

**Comment by Nyakooo** [comment]
在使用前如果有同类插件启用，需要提前关闭掉避免冲突。

可以先检查一下URL是否完整。

检查一下”全局开关“和”当前拦截规则开关“是否都启用。默认是禁用的

或者可以通过一下几点测试一下：

1、Ctrl + F5强制刷新一下浏览器
2、可以在开发者工具的网络（network）里面，通过 ☑️ 禁用缓存
3、可以先在[swagger.io](https://petstore.swagger.io) 里面尝试一下使用方式。
4、可以看下这个 [操作视频](https://www.bilibili.com/video/BV1pV4y1H7rH?vd_source=47f2c439d1dcdfef3c5f144bf04b0c01#reply127843776672)

**Comment by gongjurenzhangwei** [comment]
@g0ngjie 大佬，URL中有问号不行吗？可以根据url中的参数或者某个特征值来match吗？

**Comment by Nyakooo** [comment]
这个在最新版本已经做了优化，**问号+参数全量匹配** 或者根据 **某个特征值** 是可以的。

**[补充]**: 如果是通过刷新的方式来触发接口数据修改，在少部分情况下会出现ajax首次请求未被代理到，导致代理失败的情况。
上面提到的几种解决方案都不可行的话，可以试试通过不刷新页面的方式，看看是否正常被代理

**Comment by gongjurenzhangwei** [comment]
优秀啊，大佬，非常好的工具，感谢

**Comment by Nyakooo** [comment]
> 优秀啊，大佬，非常好的工具，感谢

😁
